name: Python

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    #runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2

    - name: 설정 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.*'

    - name: 실행
      run: |
        pip install requests
        python ./Source/python/main.py ${{ secrets.SERVICE_KEY }}

    - name: Commit files
      run: |
          git pull
          git config --local user.email "wymoon2690@gmail.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "Add changes" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.TOKEN_KEY }}
         branch: ${{ github.ref }}
